### ISSUE TITLE
Что-то не то с версионностью

### ISSUE THREAD

**Issue by pulicapus** [TemplatemonsterPlugins/rd-material-tabs#2]
Скрипт версии 1.0.2, стили 1.0.0, релизов нет, по коммитам видно только версию 1.0.1
Неплохо было бы видеть вот тут релизы https://github.com/TemplatemonsterPlugins/rd-material-tabs/releases

**Comment by raffa-sh** [comment]
All files have been updated. Version issues have been fixed - 97ef01b7650fb760a21f7d4213d7de5f580f2073
